openapi: 3.0.0
info:
  title: Management Subscriber API
  description: Management Subscriber API specification
  termsOfService: https://deepdreams.tech/terms-of-service
  contact:
    email: salari@deepdreams.tech
  license:
    name: Deep Dreams Copyright
  version: v1
paths:
  /management/subscribers/{id}:
    delete:
      summary: Delete a branch
      operationId: deleteBranchById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful operation